# SITE CONFIGURATION
baseurl: "/willshw"
# url: "https://willshw.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: William Wang
  avatar: assets/img/brain.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A growing roboticist" # used by search engines

  # Header and footer text
  header_text: >
    <p></p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
    <p>Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a></p>

  # Icons
  rss: false
  email_address: shanhewang@gmail.com # Full email address, e.g. "sam@example.com"
  github: "willshw"
  linkedin:  https://www.linkedin.com/in/williamswang/ # Full URL
  stack_exchange:  https://stackoverflow.com/users/4926659/william-wang
  twitter: "willshwang"
  vimeo:
  youtube:

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: willswang
  katex: false # Enable if using math markup
  portfolio: true
  search: true
  tags: true
  cv: true
  credit: true


  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num.html' # Pages are simple html files
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ''
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

plugins: [jekyll-paginate-v2, jekyll-seo-tag, jekyll-redirect-from]
theme: type-on-strap # If using the theme as a jekyll theme gem
# remote_theme: Sylhare/Type-on-Strap
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
